[versions]
thymeleaf = "3.0.0"
http-client = "4.0.0"
cron = "2.0.0"
admin-ui = "4.3.4"

[libraries]
lib-thymeleaf = { module = "com.enonic.lib:lib-thymeleaf", version.ref = "thymeleaf" }
lib-http-client = { module = "com.enonic.lib:lib-http-client", version.ref = "http-client" }
lib-cron = { module = "com.enonic.lib:lib-cron", version.ref = "cron" }
lib-admin-ui = { module = "com.enonic.lib:lib-admin-ui", version.ref = "admin-ui" }
